const seedProducts = [
{id:'sony',name:'Sony WH-1000XM5 Wireless Headphones',brand:'Sony',category:'Audio',rating:9.6,reviews:'4,812',price:349.99,badge:'BEST OVERALL',image:'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?auto=format&fit=crop&w=640&q=85',description:'Industry-leading noise cancellation with a wonderfully comfortable, all-day fit.',battery:'30 hours',weight:'250 g',noise:true,charging:true,bestFor:'Travel & focus'},
{id:'amazfit',name:'Amazfit GTR 4 Smart Watch',brand:'Amazfit',category:'Tech',rating:9.3,reviews:'2,145',price:167.99,badge:'BEST VALUE',image:'https://images.unsplash.com/photo-1544117519-31a4b719223d?auto=format&fit=crop&w=640&q=85',description:'A polished health and fitness tracker with excellent battery life.',battery:'14 days',weight:'34 g',noise:false,charging:true,bestFor:'Fitness tracking'},
{id:'bose',name:'Bose QuietComfort Earbuds II',brand:'Bose',category:'Audio',rating:9.2,reviews:'1,318',price:229,badge:'BEST PREMIUM',image:'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?auto=format&fit=crop&w=640&q=85',description:'Compact earbuds with personalized sound and acclaimed active noise cancellation.',battery:'24 hours',weight:'59 g',noise:true,charging:true,bestFor:'Everyday listening'},
{id:'roomba',name:'iRobot Roomba j7+ Robot Vacuum',brand:'iRobot',category:'Home',rating:9.1,reviews:'983',price:799,badge:'BEST FOR HOME',image:'https://images.unsplash.com/photo-1579567761406-4684ee0c75b6?auto=format&fit=crop&w=640&q=85',description:'A clever robot vacuum that learns your home and avoids common obstacles.',battery:'75 min',weight:'3.4 kg',noise:false,charging:true,bestFor:'Busy homes'},
{id:'canon',name:'Canon EOS R50 Mirrorless Camera',brand:'Canon',category:'Tech',rating:8.9,reviews:'1,527',price:679,badge:'BEST FOR BEGINNERS',image:'https://images.unsplash.com/photo-1516035069371-29a1b244cc32?auto=format&fit=crop&w=640&q=85',description:'An approachable mirrorless camera that makes polished photos and video easy.',battery:'440 shots',weight:'375 g',noise:false,charging:true,bestFor:'New creators'}];
let products = JSON.parse(localStorage.getItem('pickbest-products') || 'null') || seedProducts;
let categories=[{name:'Trending',icon:'flame'},{name:'Tech',icon:'monitor'},{name:'Audio',icon:'headphones'},{name:'Home',icon:'house'},{name:'Gaming',icon:'gamepad-2'},{name:'Fitness',icon:'dumbbell'},{name:'Beauty',icon:'sparkles'},{name:'Outdoors',icon:'mountain'},{name:'Software',icon:'code-2'}];


