import type { FastifyInstance } from 'fastify';
import { z } from 'zod';
import { db } from '../db/client.js';
import { audit, requireRole } from '../lib/http.js';

const subscriber = z.object({ email: z.string().trim().email().max(254).transform((email) => email.toLowerCase()) });
const categoryInput = z.object({ name: z.string().trim().min(2).max(80), icon: z.string().trim().min(1).max(48).default('tag'), isActive: z.boolean().default(true) });
const productInput = z.object({ id: z.string().trim().min(2).max(80).regex(/^[a-z0-9-]+$/), name: z.string().trim().min(2).max(180), brand: z.string().trim().min(1).max(100), category: z.string().trim().min(2).max(80), rating: z.coerce.number().min(0).max(10), reviews: z.coerce.number().int().min(0).default(0), price: z.coerce.number().min(0), badge: z.string().trim().max(60).optional().nullable(), image: z.string().url().max(2000).optional().nullable(), description: z.string().trim().max(5000).default(''), battery: z.string().trim().max(80).optional().nullable(), weight: z.string().trim().max(80).optional().nullable(), noise: z.boolean().default(false), charging: z.boolean().default(false), bestFor: z.string().trim().max(140).optional().nullable(), affiliateUrl: z.string().url().max(2000), status: z.enum(['Active', 'Draft', 'Archived']).default('Active') });
const productFields = `p.id,p.name,p.brand,c.name AS category,p.rating::float,p.review_count AS reviews,p.price::float,p.badge,p.image_url AS image,p.description,p.battery,p.weight,p.noise_cancellation AS noise,p.wireless_charging AS charging,p.best_for AS "bestFor",p.affiliate_url AS "affiliateUrl",CASE WHEN p.is_active THEN 'Active' ELSE 'Draft' END AS status`;

export async function contentRoutes(app: FastifyInstance) {
  app.get('/categories', async () => ({ items: (await db.query('SELECT name, icon FROM categories WHERE is_active = true ORDER BY name')).rows }));
  app.get('/products', async () => ({ items: (await db.query(`SELECT ${productFields} FROM products p JOIN categories c ON c.id=p.category_id WHERE p.is_active=true AND c.is_active=true ORDER BY p.rating DESC,p.name`)).rows }));
  app.post('/newsletter/subscribers', { config: { rateLimit: { max: 5, timeWindow: '1 hour' } } }, async (request, reply) => { const parsed=subscriber.safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',message:'A valid email address is required.'}); await db.query(`INSERT INTO newsletter_subscribers (email,status) VALUES ($1,'active') ON CONFLICT (email) DO UPDATE SET status='active',subscribed_at=now()`,[parsed.data.email]); return reply.code(201).send({ok:true}); });

  app.get('/admin/categories', { preHandler: requireRole('admin') }, async () => ({ items: (await db.query('SELECT name, icon, is_active AS "isActive" FROM categories ORDER BY name')).rows }));
  app.post('/admin/categories', { preHandler: requireRole('admin') }, async (request, reply) => { const parsed=categoryInput.safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',message:'Invalid category data.'}); const result=await db.query('INSERT INTO categories (name,icon,is_active) VALUES ($1,$2,$3) RETURNING name,icon,is_active AS "isActive"',[parsed.data.name,parsed.data.icon,parsed.data.isActive]); await audit(request.user.sub,'category.created','category',result.rows[0].name); return reply.code(201).send({item:result.rows[0]}); });
  app.delete('/admin/categories/:name', { preHandler: requireRole('admin') }, async (request, reply) => { const parsed=z.object({name:z.string().min(2).max(80)}).safeParse(request.params); if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',message:'Invalid category.'}); const inUse=await db.query('SELECT 1 FROM products p JOIN categories c ON c.id=p.category_id WHERE c.name=$1 LIMIT 1',[parsed.data.name]); if(inUse.rowCount)return reply.code(409).send({error:'CATEGORY_IN_USE',message:'Delete or move its products first.'}); const result=await db.query('DELETE FROM categories WHERE name=$1 RETURNING name',[parsed.data.name]); if(!result.rowCount)return reply.code(404).send({error:'NOT_FOUND',message:'Category not found.'}); await audit(request.user.sub,'category.deleted','category',parsed.data.name); return {ok:true}; });

  app.get('/admin/products', { preHandler: requireRole('admin') }, async () => ({ items: (await db.query(`SELECT ${productFields} FROM products p JOIN categories c ON c.id=p.category_id ORDER BY p.rating DESC,p.name`)).rows }));
  app.post('/admin/products', { preHandler: requireRole('admin') }, async (request, reply) => { const parsed=productInput.safeParse(request.body); if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',message:'Invalid product data.'}); const category=await db.query<{id:string}>('SELECT id FROM categories WHERE name=$1',[parsed.data.category]); if(!category.rowCount)return reply.code(400).send({error:'CATEGORY_NOT_FOUND',message:'Choose an existing category.'}); const p=parsed.data; const result=await db.query(`INSERT INTO products (id,name,brand,category_id,rating,review_count,price,badge,image_url,description,battery,weight,noise_cancellation,wireless_charging,best_for,affiliate_url,is_active) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17) RETURNING id`,[p.id,p.name,p.brand,category.rows[0].id,p.rating,p.reviews,p.price,p.badge,p.image,p.description,p.battery,p.weight,p.noise,p.charging,p.bestFor,p.affiliateUrl,p.status==='Active']); await audit(request.user.sub,'product.created','product',result.rows[0].id); return reply.code(201).send({item:{...p}}); });
  app.put('/admin/products/:id', { preHandler: requireRole('admin') }, async (request, reply) => { const params=z.object({id:z.string().min(2).max(80)}).safeParse(request.params); const parsed=productInput.safeParse({...((request.body||{}) as object),id:(request.params as {id:string}).id}); if(!params.success||!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',message:'Invalid product data.'}); const category=await db.query<{id:string}>('SELECT id FROM categories WHERE name=$1',[parsed.data.category]); if(!category.rowCount)return reply.code(400).send({error:'CATEGORY_NOT_FOUND',message:'Choose an existing category.'}); const p=parsed.data; const result=await db.query(`UPDATE products SET name=$2,brand=$3,category_id=$4,rating=$5,review_count=$6,price=$7,badge=$8,image_url=$9,description=$10,battery=$11,weight=$12,noise_cancellation=$13,wireless_charging=$14,best_for=$15,affiliate_url=$16,is_active=$17,updated_at=now() WHERE id=$1 RETURNING id`,[p.id,p.name,p.brand,category.rows[0].id,p.rating,p.reviews,p.price,p.badge,p.image,p.description,p.battery,p.weight,p.noise,p.charging,p.bestFor,p.affiliateUrl,p.status==='Active']); if(!result.rowCount)return reply.code(404).send({error:'NOT_FOUND',message:'Product not found.'}); await audit(request.user.sub,'product.updated','product',p.id); return {item:p}; });
  app.delete('/admin/products/:id', { preHandler: requireRole('admin') }, async (request, reply) => { const parsed=z.object({id:z.string().min(2).max(80)}).safeParse(request.params); if(!parsed.success)return reply.code(400).send({error:'VALIDATION_ERROR',message:'Invalid product.'}); const result=await db.query('DELETE FROM products WHERE id=$1 RETURNING id',[parsed.data.id]); if(!result.rowCount)return reply.code(404).send({error:'NOT_FOUND',message:'Product not found.'}); await audit(request.user.sub,'product.deleted','product',parsed.data.id); return {ok:true}; });
}